# frozen_string_literal: true

module DiscourseSevillaFixtures
  # Responsible for building the title and raw markdown body for a
  # Discourse match-thread topic, including the [event][/event] block
  # required by the Discourse Events plugin.
  class FixturePostBuilder

    COMPETITION_EMOJI = {
      "Primera Division"              => "🇪🇸",
      "La Liga"                       => "🇪🇸",
      "Copa del Rey"                  => "🏆",
      "UEFA Europa League"            => "🇪🇺",
      "UEFA Europa Conference League" => "🇪🇺",
      "UEFA Champions League"         => "⭐",
      "Supercopa de España"           => "🏅"
    }.freeze

    DEFAULT_EMOJI = "⚽"

    # ── Public Interface ──────────────────────────────────────────────────────

    # @param fixture [SevillaFixture]
    # @return [Hash] with keys :title and :raw
    def build(fixture)
      {
        title: build_title(fixture),
        raw:   build_body(fixture)
      }
    end

    # ── Private Helpers ───────────────────────────────────────────────────────

    private

    # Title format:
    #   [Competition Emblem img] Competition – Matchday N | Sevilla FC [crest] vs/@ Opponent [crest]
    # Falls back gracefully if emblem/crest URLs are not available.
    def build_title(fixture)
      matchday_part = fixture.matchday.present? ? " - Matchday #{fixture.matchday}" : ""
      connector     = fixture.home_game? ? "vs" : "at"

      "#{fixture.competition}#{matchday_part} | Sevilla FC #{connector} #{fixture.opponent}"
    end

    def build_body(fixture)
      timezone   = SiteSetting.sevilla_fixtures_event_timezone
      start_time = format_event_time(fixture.kickoff_at, timezone)
      end_time   = format_event_time(fixture.kickoff_at + 2.hours, timezone)

      sections = []

      # ── Discourse Events plugin block ─────────────────────────────────────
      sections << <<~EVENT.strip
        [event start="#{start_time}" end="#{end_time}" status="public" timezone="#{timezone}" allowedGroups="trust_level_0"]
        [/event]
      EVENT

      # ── Match info table ──────────────────────────────────────────────────
      sections << build_match_info_table(fixture)

      # ── Discussion prompt ─────────────────────────────────────────────────
      sections << build_discussion_prompt(fixture)

      sections.join("\n\n")
    end

    def build_match_info_table(fixture)
      kickoff_display = fixture.kickoff_at&.in_time_zone(
        SiteSetting.sevilla_fixtures_event_timezone
      )&.strftime("%A, %B %-d %Y at %H:%M %Z") || "TBD"

      venue_line    = fixture.venue.present?    ? "| **Venue**    | #{fixture.venue} |"    : ""
      matchday_line = fixture.matchday.present? ? "| **Matchday** | #{fixture.matchday} |" : ""

      home_crest = fixture.home_team_crest.present? ? "<img src='#{fixture.home_team_crest}' width='75'/>" : ""
      away_crest = fixture.away_team_crest.present? ? "<img src='#{fixture.away_team_crest}' width='75'/>" : ""

      <<~TABLE.strip
    ## Match Details

    | | |
    |---|---|
    | **Competition** | #{fixture.competition} |
    #{matchday_line}
    | **Home**        | #{fixture.home_team} #{home_crest} |
    | **Away**        | #{fixture.away_team} #{away_crest} |
    | **Kickoff**     | #{kickoff_display} |
    #{venue_line}
  TABLE
    end

    def build_discussion_prompt(fixture)
      <<~PROMPT.strip
        ## Match Thread

        Use this thread to discuss everything about today's match:

        - **Starting XI predictions** – Who do you want to see in the lineup?
        - **Tactical thoughts** – How should Sevilla set up?
        - **Live reactions** – Share your thoughts as the match unfolds
        - **Post-match analysis** – Player ratings, key moments, and what it means for the table

        *Vamos Mi Sevilla! 🔴⚪*

        ---
        *This thread was automatically generated by the MonchisMen match scheduler.*
      PROMPT
    end

    def competition_emoji(competition_name)
      COMPETITION_EMOJI.find { |k, _| competition_name.include?(k) }&.last || DEFAULT_EMOJI
    end

    # Formats a Time object into the string format expected by the Events plugin:
    # "YYYY-MM-DD HH:MM"
    def format_event_time(time, timezone)
      time.in_time_zone(timezone).strftime("%Y-%m-%d %H:%M")
    end
  end
end